# Generated by Django 3.2.3 on 2021-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('current_cost', models.FloatField(default=0)),
                ('old_cost', models.FloatField(default=0)),
                ('cost_diff', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('cost_diff', '-created'),
            },
        ),
    ]
